name: Deploy Reflect

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '18.x'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: npm install
        run: |
          npm install

      - name: publish
        env:
          REFLECT_AUTH_KEY: ${{ secrets.REFLECT_AUTH_KEY }}
        run: |
          cd examples/basic && npx reflect publish --auth-key-from-env=REFLECT_AUTH_KEY
